version: '3.3'
services:
  app:
    image: cyalater/xcloud:v1
    restart: always
    volumes:
      - static_value:/app/static/
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./x-cloud.crt:/etc/ssl/x-cloud.crt
      - ./x-cloud.key:/etc/ssl/x-cloud.key
    depends_on:
      - app

volumes:
  static_value:
