name: CI/CD

on: 
  push:
    branches: [master, main]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r cloudpass/requirements.txt

      - name: Test with flake8
        run:
          python -m flake8

  build_and_push_backend:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: True
          context: ./cloudpass/
          tags: ${{ secrets.DOCKER_LOGIN }}/xcloud:v1